### ISSUE TITLE
No visible @interface for 'HTTransmitterClient' declares the selector 'transmittingLocation'

### ISSUE THREAD

**Issue by doominiek** [hypertrack/react-native-hypertrack#8] opened 2017-02-16 17:15 UTC
I got this error in RNHyperTrack.m with React Native 0.36.0
No visible @interface for 'HTTransmitterClient' declares the selector 'transmittingLocation'

**Comment by arjun27** [comment] 2017-02-16 17:25
Hey @doominiek, looks like the issue is due to an old version of the iOS native SDK. The latest version is 0.13.8. If you do a `pod update` inside the `ios` directory of the RN project this should be fixed.

Let me know that solved it

**Closed by arjun27** 2017-02-16 17:25 UTC

**Comment by doominiek** [comment] 2017-02-16 17:46
Thanks for your quick response! Pod update did work for me!
